- name: Install default packages
  apt: name={{ item }}
  with_items:
    - unzip
    - python-pip
    - elinks
    - lynx
    - links

- name: Make sure ansible is run after system boot
  lineinfile:
    dest=/etc/rc.local
    insertbefore='exit 0'
    line='/usr/local/bin/ansible-playbook /etc/ansible/site.yml'

- name: Run ansible-playbook every 30 minutes
  cron:
    job='/usr/local/bin/ansible-playbook /etc/ansible/site.yml'
    minute='1,31'
    name='Run ansible'

- name: Ping google.com every 5 minuten to keep the connection open
  cron:
    job='ping -c 1 www.google.com'
    minute='*/5'
    name='Ping google'
