- name: Run ansible-playbook after reboot
  cron:
    job='/usr/local/bin/ansible-playbook /etc/ansible/site.yml'
    special_time=reboot
    name='Run ansible after reboot'

- name: Run ansible-playbook every 30 minutes
  cron:
    job='/usr/local/bin/ansible-playbook /etc/ansible/site.yml'
    minute='1,31'
    name='Run ansible'

- name: Ping google.com every 5 minuten to keep the connection open
  cron:
    job='ping -c 1 www.google.com'
    minute='*/5'
    name='Ping google'
