- name: Check kernel routing status
  command: cat /proc/sys/net/ipv4/ip_forward
  register: ip_forward
  changed_when: False

- name: Enable routing in the kernel
  shell: echo 1 > /proc/sys/net/ipv4/ip_forward
  when: ip_forward.stdout == '0'

- name: Persist routing so it is active after reboot
  lineinfile:
    dest=/etc/sysctl.conf
    line=net.ipv4.ip_forward=1

# - name: Save iptables rules to config file
#   template:
#     src=iptables.config
#     dest=

# - name: Make sure the iptables config is restored when the network is started
