- name: Configure network interfaces
  template:
    src=interfaces
    dest=/etc/network/interfaces
  register: result

- name: Configure upstream network
  template:
    src=wpa_supplicant.conf
    dest=/etc/wpa_supplicant/wpa_supplicant.conf
  register: result_wpa

- name: Restart network interfaces
  shell: ifdown -a && ifup -a
  when: result|changed or result_wpa|changed
